namespace eCOFIN.Application.DTOs
{
    public class CfnRepcontbDto
    {
        public string Accountcode { get; set; }
        public decimal? CbCredit1 { get; set; }
        public decimal? CbCredit10 { get; set; }
        public decimal? CbCredit11 { get; set; }
        public decimal? CbCredit12 { get; set; }
        public decimal? CbCredit13 { get; set; }
        public decimal? CbCredit14 { get; set; }
        public decimal? CbCredit15 { get; set; }
        public decimal? CbCredit16 { get; set; }
        public decimal? CbCredit17 { get; set; }
        public decimal? CbCredit18 { get; set; }
        public decimal? CbCredit19 { get; set; }
        public decimal? CbCredit2 { get; set; }
        public decimal? CbCredit20 { get; set; }
        public decimal? CbCredit3 { get; set; }
        public decimal? CbCredit4 { get; set; }
        public decimal? CbCredit5 { get; set; }
        public decimal? CbCredit6 { get; set; }
        public decimal? CbCredit7 { get; set; }
        public decimal? CbCredit8 { get; set; }
        public decimal? CbCredit9 { get; set; }
        public string CbDbcr1 { get; set; }
        public string CbDbcr10 { get; set; }
        public string CbDbcr11 { get; set; }
        public string CbDbcr12 { get; set; }
        public string CbDbcr13 { get; set; }
        public string CbDbcr14 { get; set; }
        public string CbDbcr15 { get; set; }
        public string CbDbcr16 { get; set; }
        public string CbDbcr17 { get; set; }
        public string CbDbcr18 { get; set; }
        public string CbDbcr19 { get; set; }
        public string CbDbcr2 { get; set; }
        public string CbDbcr20 { get; set; }
        public string CbDbcr3 { get; set; }
        public string CbDbcr4 { get; set; }
        public string CbDbcr5 { get; set; }
        public string CbDbcr6 { get; set; }
        public string CbDbcr7 { get; set; }
        public string CbDbcr8 { get; set; }
        public string CbDbcr9 { get; set; }
        public decimal? CbDebit1 { get; set; }
        public decimal? CbDebit10 { get; set; }
        public decimal? CbDebit11 { get; set; }
        public decimal? CbDebit12 { get; set; }
        public decimal? CbDebit13 { get; set; }
        public decimal? CbDebit14 { get; set; }
        public decimal? CbDebit15 { get; set; }
        public decimal? CbDebit16 { get; set; }
        public decimal? CbDebit17 { get; set; }
        public decimal? CbDebit18 { get; set; }
        public decimal? CbDebit19 { get; set; }
        public decimal? CbDebit2 { get; set; }
        public decimal? CbDebit20 { get; set; }
        public decimal? CbDebit3 { get; set; }
        public decimal? CbDebit4 { get; set; }
        public decimal? CbDebit5 { get; set; }
        public decimal? CbDebit6 { get; set; }
        public decimal? CbDebit7 { get; set; }
        public decimal? CbDebit8 { get; set; }
        public decimal? CbDebit9 { get; set; }
        public string Description { get; set; }
        public decimal? TotCredit { get; set; }
        public string TotDbcr { get; set; }
        public decimal? TotDebit { get; set; }
    }
}
