namespace eCOFIN.Application.DTOs
{
    public class CfnVoucherheaderDto
    {
        public string CtrlOnholdno { get; set; }
        public string Accountcode { get; set; }
        public string Assetclassification { get; set; }
        public string Assetgroup { get; set; }
        public string Assetlocationcode { get; set; }
        public string Assetnumber { get; set; }
        public decimal? BankRate { get; set; }
        public string Bankaccount { get; set; }
        public string Bankcode { get; set; }
        public DateTime? Bankdocumentdate { get; set; }
        public string Bankdocumentno { get; set; }
        public string Bankname { get; set; }
        public string Billpassingappl { get; set; }
        public string Cashaccount { get; set; }
        public string Cepref { get; set; }
        public string Chqauthorize { get; set; }
        public string Chqgenerate { get; set; }
        public string Costcentrecode { get; set; }
        public string Costcentrecodedescription { get; set; }
        public string Costtype { get; set; }
        public string Costtypedescription { get; set; }
        public string CreditvchrSystemtype { get; set; }
        public string CreditvchrType { get; set; }
        public string CtrlAccperiod { get; set; }
        public string CtrlCancelflag { get; set; }
        public DateTime? CtrlCreatedon { get; set; }
        public DateTime? CtrlLastupdate { get; set; }
        public string CtrlLocationcode { get; set; }
        public string CtrlLogextract { get; set; }
        public string CtrlLogextracttype { get; set; }
        public string CtrlStatus { get; set; }
        public string CtrlTrglocationcode { get; set; }
        public string CtrlUsername { get; set; }
        public string Currencycode { get; set; }
        public string Description { get; set; }
        public string Employeecode { get; set; }
        public string Employeename { get; set; }
        public decimal? Entertainment { get; set; }
        public decimal? Exchangerate { get; set; }
        public string Expensetype { get; set; }
        public string Expensetypedescription { get; set; }
        public string Favourof { get; set; }
        public decimal? Foreigncurr { get; set; }
        public string Gapcno { get; set; }
        public string GivvchrsysType { get; set; }
        public string Givvchrtype { get; set; }
        public decimal? Hotel { get; set; }
        public string Instrument { get; set; }
        public decimal? Instrumentbookno { get; set; }
        public string Instrumentcategory { get; set; }
        public DateTime? Instrumentdate { get; set; }
        public string Instrumentno { get; set; }
        public string InvctrlAccperiod { get; set; }
        public DateTime? Lcdate { get; set; }
        public string Lcnumber { get; set; }
        public decimal? Localconveyance { get; set; }
        public string Paidto { get; set; }
        public string Partycode { get; set; }
        public string Productcode { get; set; }
        public string Productdescription { get; set; }
        public string Purchasebilltype { get; set; }
        public decimal? Sanctionedamount { get; set; }
        public string Sanctionno { get; set; }
        public string Segcode2 { get; set; }
        public string Subaccountcode { get; set; }
        public string Subaccountcodedescription { get; set; }
        public decimal? Sundries { get; set; }
        public decimal? Travelamount { get; set; }
        public decimal? Traveltotal { get; set; }
        public string Traveltype { get; set; }
        public string TrvlEmployeeacc { get; set; }
        public string TrvlSanctionno { get; set; }
        public string VchrCategory { get; set; }
        public DateTime? VchrDate { get; set; }
        public string VchrNarration { get; set; }
        public string VchrNumber { get; set; }
        public DateTime? VchrRefdate { get; set; }
        public string VchrRefnumber { get; set; }
        public string VchrSyscategory { get; set; }
        public decimal? VchrTotalamount { get; set; }
        public string VchrType { get; set; }
        public string Vendorcode { get; set; }
        public string Vendorname { get; set; }
        public string Warehousecode { get; set; }
    }
}
