namespace eCOFIN.Application.DTOs
{
    public class CustomerDto
    {
        public string Custcode { get; set; }
        public string Active { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public int AirCreditDays { get; set; }
        public string AirDeliveryTerms { get; set; }
        public string AirInsurence { get; set; }
        public string AirPaymentTerms { get; set; }
        public string AirPaymentType { get; set; }
        public string AirPlaDel { get; set; }
        public string AirPlaRecPreCarr { get; set; }
        public string AirPortDis { get; set; }
        public string AirPortLoad { get; set; }
        public string AirPreCarr { get; set; }
        public string AllowMultiplePoToInvoice { get; set; }
        public string AnnexureInvoiceAttach { get; set; }
        public string AttachInvoiceReport { get; set; }
        public string AutoMailOs { get; set; }
        public DateTime? AutoMailOsLastSent { get; set; }
        public string BackOfficePerson { get; set; }
        public string Bkname { get; set; }
        public string BrandCode { get; set; }
        public int? CallOffReminderInDays { get; set; }
        public string CategoryType { get; set; }
        public string Cess { get; set; }
        public double? Cessval { get; set; }
        public string Cform { get; set; }
        public string CinNo { get; set; }
        public string City { get; set; }
        public string ClientName { get; set; }
        public string ClubOrders { get; set; }
        public string Coname { get; set; }
        public string Conper0 { get; set; }
        public string ContactPerson { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string Couriername { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public double? CreditAmount { get; set; }
        public int? CreditDays { get; set; }
        public string Cst { get; set; }
        public double? CstVal { get; set; }
        public DateTime? Cstdate { get; set; }
        public string Ct3Add1 { get; set; }
        public string Ct3Add2 { get; set; }
        public double? Ct3Amount { get; set; }
        public string Ct3Fromname { get; set; }
        public string Ct3RegNo { get; set; }
        public string Currency { get; set; }
        public string CurrencyCode { get; set; }
        public int CustAdvanceResDays { get; set; }
        public string CustNameCaseName { get; set; }
        public int CustProformaResDays { get; set; }
        public string CustType { get; set; }
        public string CustUpdate { get; set; }
        public string Custname { get; set; }
        public string CustomerSubType { get; set; }
        public double CyPoturnOver { get; set; }
        public double CyTurnOver { get; set; }
        public int? Days { get; set; }
        public string DealerCode { get; set; }
        public string DelCond { get; set; }
        public string DeliveryTerms { get; set; }
        public string DisplayName { get; set; }
        public int? Distance { get; set; }
        public string Ecc { get; set; }
        public double? Ed { get; set; }
        public string Email { get; set; }
        public string EmailInvCopy { get; set; }
        public string EndCustomerRequired { get; set; }
        public string EorinoRequired { get; set; }
        public string FamilyType { get; set; }
        public string FaxNo0 { get; set; }
        public string Faxno { get; set; }
        public double? FlucFactor { get; set; }
        public string FormerConame { get; set; }
        public DateTime? FormerConameDateTill { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
        public DateTime? GsBondDate { get; set; }
        public string GsBondNo { get; set; }
        public DateTime? GsValidTo { get; set; }
        public string GstNo { get; set; }
        public string InspectionTerms { get; set; }
        public string InvMultiPo { get; set; }
        public string Kst { get; set; }
        public double? KstVal { get; set; }
        public DateTime? Kstdate { get; set; }
        public string LabelingInst { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public string LoiAllowed { get; set; }
        public string MacAddress { get; set; }
        public string Madd1 { get; set; }
        public string Madd2 { get; set; }
        public string Mail0 { get; set; }
        public string MarkingInst { get; set; }
        public int MaxLineItemsInInvoice { get; set; }
        public string Mcity { get; set; }
        public string McontactPerson { get; set; }
        public string Mcountry { get; set; }
        public string Memail { get; set; }
        public string Mfaxno { get; set; }
        public string Modeship { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Mphoneno { get; set; }
        public string Mpin { get; set; }
        public string Mstate { get; set; }
        public string Mtown { get; set; }
        public string Mzone { get; set; }
        public string OldCustCode { get; set; }
        public string OrderRemarks { get; set; }
        public string Packaging { get; set; }
        public string PackingInst { get; set; }
        public string PanNo { get; set; }
        public string PaymentType { get; set; }
        public string Payterm { get; set; }
        public string PermanentCustomer { get; set; }
        public int PfinvExpiryDays { get; set; }
        public string PhoneNo0 { get; set; }
        public string Phoneno { get; set; }
        public string Pincode { get; set; }
        public string PriceTypeCode { get; set; }
        public string Pricetype { get; set; }
        public string PromotionalItemClass { get; set; }
        public double PyPoturnOver { get; set; }
        public double PyTurnOver { get; set; }
        public string Range { get; set; }
        public string Refno { get; set; }
        public string Remarks { get; set; }
        public string RexApply { get; set; }
        public string RoadPermit { get; set; }
        public long RowNo { get; set; }
        public string SalesEng { get; set; }
        public string SalesEngEmpNo { get; set; }
        public int SeaCreditDays { get; set; }
        public string SeaDeliveryTerms { get; set; }
        public string SeaInsurence { get; set; }
        public string SeaPaymentTerms { get; set; }
        public string SeaPaymentType { get; set; }
        public string SeaPlaDel { get; set; }
        public string SeaPlaRecPreCarr { get; set; }
        public string SeaPortDis { get; set; }
        public string SeaPortLoad { get; set; }
        public string SeaPreCarr { get; set; }
        public string Segment { get; set; }
        public string Sez { get; set; }
        public string SignatureRequired { get; set; }
        public string State { get; set; }
        public string StockName { get; set; }
        public string TinNo { get; set; }
        public string Type { get; set; }
        public string Typeindu { get; set; }
        public string Url { get; set; }
        public string Vencode { get; set; }
        public string WebSite { get; set; }
        public DateTime? WhLicDate { get; set; }
        public string WhLicNo { get; set; }
        public DateTime? WhValidTo { get; set; }
        public string Zone { get; set; }
        public string ZoneCategory { get; set; }
    }
}
