namespace eCOFIN.Application.DTOs
{
    public class GinPriceImportDto
    {
        public string GinNo { get; set; }
        public double? AssValue { get; set; }
        public double? AssWbcdVal { get; set; }
        public double? BasicValue { get; set; }
        public double? BcdIval { get; set; }
        public double? BcdOc { get; set; }
        public double? BcdPer { get; set; }
        public double? BcdVal { get; set; }
        public double? BcdecessPer { get; set; }
        public double? BcdecessVal { get; set; }
        public double? BcdgstPer { get; set; }
        public double? BcdshecessPer { get; set; }
        public double? BcdshecessVal { get; set; }
        public double? Bd { get; set; }
        public double? BdCess { get; set; }
        public double? BdCessPer { get; set; }
        public double? BdPer { get; set; }
        public string CaccCode { get; set; }
        public double? CbasicNonTaxVal { get; set; }
        public double? CbasicTaxVal { get; set; }
        public double? CcgstPer { get; set; }
        public double? CcgstVal { get; set; }
        public double? Ced { get; set; }
        public double? CedCess { get; set; }
        public double? CfCharge { get; set; }
        public double? CfFreight { get; set; }
        public double? CfInsurance { get; set; }
        public double? CfPostage { get; set; }
        public double? Cif { get; set; }
        public double? CifOc { get; set; }
        public double? CigstPer { get; set; }
        public double? CigstVal { get; set; }
        public double? ClearanceVal { get; set; }
        public double? CocVal { get; set; }
        public double? ConversionRate { get; set; }
        public string CsacCode { get; set; }
        public double? CsgstPer { get; set; }
        public double? CsgstVal { get; set; }
        public string CsuppCode { get; set; }
        public double? CtdsPer { get; set; }
        public double? CtdsVal { get; set; }
        public string CurrencyCode { get; set; }
        public double? Cvd { get; set; }
        public double? CvdCess { get; set; }
        public double? CvdCessPer { get; set; }
        public double? CvdPer { get; set; }
        public string EnteredBy { get; set; }
        public DateTime? EnteredDate { get; set; }
        public double? EtComp { get; set; }
        public double? EtConTool { get; set; }
        public double? EtPlaMac { get; set; }
        public string FaccCode { get; set; }
        public double? FbasicNonTaxVal { get; set; }
        public double? FbasicTaxVal { get; set; }
        public double? FcgstPer { get; set; }
        public double? FcgstVal { get; set; }
        public double? FigstPer { get; set; }
        public double? FigstVal { get; set; }
        public double? FocVal { get; set; }
        public double? Freight { get; set; }
        public double? FreightVal { get; set; }
        public string FsacCode { get; set; }
        public double? FsgstPer { get; set; }
        public double? FsgstVal { get; set; }
        public string FsuppCode { get; set; }
        public double? FtdsPer { get; set; }
        public double? FtdsVal { get; set; }
        public double? HandlingChargesPer { get; set; }
        public double? HandlingChargesVal { get; set; }
        public double? Insurance { get; set; }
        public double? InvValue { get; set; }
        public double LanChar { get; set; }
        public double? LanCost { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public double? ModRec { get; set; }
        public double? ModRecCess { get; set; }
        public double? OtherCharges { get; set; }
        public double? PayToSupplier { get; set; }
        public double? Pf { get; set; }
        public string PoNo { get; set; }
        public long RowId { get; set; }
        public double? Sad { get; set; }
        public double? SadPer { get; set; }
    }
}
