namespace eCOFIN.Application.DTOs
{
    public class InvMainDto
    {
        public string Slno { get; set; }
        public DateTime? AckDate { get; set; }
        public string AckNo { get; set; }
        public string Ar4 { get; set; }
        public double AssessValue { get; set; }
        public double BcdPer { get; set; }
        public string Book { get; set; }
        public string BtiGinno { get; set; }
        public double? Cess { get; set; }
        public double? CessEd { get; set; }
        public double CessPer { get; set; }
        public double? CgstPerM { get; set; }
        public string ClientName { get; set; }
        public string Commercial { get; set; }
        public string CompanyName { get; set; }
        public string ConsigneeCode { get; set; }
        public string CreatedBy { get; set; }
        public double? Cst { get; set; }
        public string Ct3No { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double? CurrencyRate { get; set; }
        public double CusCess { get; set; }
        public double Cusduty { get; set; }
        public string CustCode { get; set; }
        public string CustRec { get; set; }
        public DateTime? CustRecDate { get; set; }
        public string CustRecNo { get; set; }
        public string CustType { get; set; }
        public double CvdCessValue { get; set; }
        public double CvdCessValue2 { get; set; }
        public double CvdValue { get; set; }
        public string Debit { get; set; }
        public DateTime? DebitDate { get; set; }
        public int? DebitNo { get; set; }
        public string DeliveryTerms { get; set; }
        public double DiscountPer { get; set; }
        public string DisplayDiscount { get; set; }
        public double? Edcess2Perc { get; set; }
        public double? Edcess2Value { get; set; }
        public double? EdcessPerc { get; set; }
        public double? EdcessValue { get; set; }
        public string EwbNo { get; set; }
        public double ExemptedDuty { get; set; }
        public string FetteSlNo { get; set; }
        public double? Freight { get; set; }
        public double FreightCharges { get; set; }
        public string Ftype { get; set; }
        public string GpNo { get; set; }
        public string GroupInvoice { get; set; }
        public double? GstPerM { get; set; }
        public string GstType { get; set; }
        public double HecessPer { get; set; }
        public string HsnCodeM { get; set; }
        public double? IgstPerM { get; set; }
        public string IndigenousInv { get; set; }
        public double? Insurance { get; set; }
        public double InsuranceCharges { get; set; }
        public string InvActive { get; set; }
        public string InvMultiPo { get; set; }
        public string InvSwipeNo { get; set; }
        public string IrnNo { get; set; }
        public string IrnQrcode { get; set; }
        public string IsPromoOrder { get; set; }
        public string ItemSegment { get; set; }
        public double? KrishiKCessP { get; set; }
        public double? Kst { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public string LocFetteInvoice { get; set; }
        public string MacAddress { get; set; }
        public string Mode { get; set; }
        public double OrderValue { get; set; }
        public double? OriginCharge { get; set; }
        public double OriginCharges { get; set; }
        public double OtherChargesOutSideGst { get; set; }
        public double PackForwardCharges { get; set; }
        public double PackingCharges { get; set; }
        public double PayDutyCessValue { get; set; }
        public double PayDutyCessValue2 { get; set; }
        public double? PayReceiptAmt { get; set; }
        public string PayReceiptId { get; set; }
        public double PayableDuty { get; set; }
        public string PaymentTerms { get; set; }
        public DateTime? PcDate { get; set; }
        public string PcNo { get; set; }
        public double PfCharges { get; set; }
        public string PonoList { get; set; }
        public string PromoDescription { get; set; }
        public string Receiving { get; set; }
        public string Regn { get; set; }
        public string Remarks { get; set; }
        public DateTime? RemovalDate { get; set; }
        public string RemovalTime { get; set; }
        public long RowNo { get; set; }
        public string SalesEng { get; set; }
        public string SalesEngineer { get; set; }
        public double? SbharatCessP { get; set; }
        public double? ServiceTax { get; set; }
        public double? SgstPerM { get; set; }
        public string SpecialOrder { get; set; }
        public DateTime? StartDate { get; set; }
        public string StartTime { get; set; }
        public string SubSubType { get; set; }
        public string SubType { get; set; }
        public string Tarrif { get; set; }
        public double TcsPer { get; set; }
        public double TotalPayableDuty { get; set; }
        public double TotalValue { get; set; }
        public string Type { get; set; }
        public string VSlNo { get; set; }
        public double VatValue { get; set; }
        public double VatonDuty { get; set; }
        public double VcdPer { get; set; }
    }
}
