namespace eCOFIN.Application.DTOs
{
    public class PersonelDto
    {
        public string EmpNo { get; set; }
        public string AltEmailId { get; set; }
        public string AltMobile { get; set; }
        public string AltPhone { get; set; }
        public DateTime? AutoMailOpLastSent { get; set; }
        public DateTime? AutoMailQrLastSent { get; set; }
        public string Bankaccno { get; set; }
        public string Bankcode { get; set; }
        public string BloodGroup { get; set; }
        public string Caste { get; set; }
        public string CellCode { get; set; }
        public string CellSn { get; set; }
        public string CompanyCode { get; set; }
        public string CompensatoryLeaveAllowed { get; set; }
        public string Costcentre { get; set; }
        public string Dept { get; set; }
        public string DeptCode { get; set; }
        public string Designation { get; set; }
        public DateTime? Dob { get; set; }
        public DateTime? Doc { get; set; }
        public DateTime? Doi { get; set; }
        public DateTime? Doj { get; set; }
        public string EmailId { get; set; }
        public string EmailIdPer { get; set; }
        public string EmpActive { get; set; }
        public string EmpBarCode { get; set; }
        public string EmpBarCodeOld { get; set; }
        public string EmpCode { get; set; }
        public string Emptype { get; set; }
        public string Esidispensary { get; set; }
        public string Esino { get; set; }
        public string Fname { get; set; }
        public string FrequentTraveller { get; set; }
        public int? HLevel { get; set; }
        public string Hposition { get; set; }
        public string HrRights { get; set; }
        public string Insurenceno { get; set; }
        public string ItaxNo { get; set; }
        public string Jobdes { get; set; }
        public string Jobstat { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public string Martialstatus { get; set; }
        public string Mobile { get; set; }
        public string MobilePer { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Padd1 { get; set; }
        public string Padd2 { get; set; }
        public string Pager { get; set; }
        public string Passportno { get; set; }
        public string Paymode { get; set; }
        public string Pcity { get; set; }
        public string Pcountry { get; set; }
        public string Pfno { get; set; }
        public decimal? Pincode { get; set; }
        public string Position { get; set; }
        public DateTime? Ppdoi { get; set; }
        public DateTime? Ppvalid { get; set; }
        public string Pstate { get; set; }
        public string Religion { get; set; }
        public string ReportTo { get; set; }
        public string ReportToManage { get; set; }
        public DateTime? Resgdate { get; set; }
        public int? Resignation { get; set; }
        public string Resreason { get; set; }
        public long RowNo { get; set; }
        public string Salgrade { get; set; }
        public string Saltype { get; set; }
        public string Section { get; set; }
        public string SectionCode { get; set; }
        public string Sex { get; set; }
        public string ShiftType { get; set; }
        public int? Subnos { get; set; }
        public string SystemLoginId { get; set; }
        public string Tadd1 { get; set; }
        public string Tadd2 { get; set; }
        public string Tcity { get; set; }
        public string Tel { get; set; }
        public string Tpincode { get; set; }
        public string Tstate { get; set; }
        public string Yearsofexperience { get; set; }
    }
}
